version: "3"
services:
  client:
    build: .
    labels:
      __DOMAIN__: "__PROJECT_NAME__"
    volumes:
      - ./:/usr/src/app
    ports:
      - __ANGULAR_PORT__:4200
      - __KARMA_PORT__:9876
    command: bash -c "npm install && npm run serve"
#    command: bash -c "yarn install && yarn serve"
