version: "3"
services:
  client:
    build: .
    labels:
      {{DOMAIN}}: "{{PROJECT_NAME}}"
    volumes:
      - ./:/usr/src/app
    ports:
      - {{ANGULAR_PORT}}:4200
      - {{KARMA_PORT}}:9876
    command: bash -c "npm install && npm run serve"
